### ISSUE TITLE
Jaeger Chart :- need custom labels support in query-ing.yaml

### ISSUE THREAD

**Issue by rgssingh** [jaegertracing/helm-charts#104]
Hi Team,

Can you please provide the custom labels support in query-ing.yaml. 

For example :-

{{- toYaml .Values.query.ingress.labels | nindent 4 }}

Thanks

**Comment by naseemkullah** [comment]
Hi @rgssingh, would you be willing to open a PR to add this functionality?
Also I am curious what is your use case if you don't mind sharing?

**Comment by rgssingh** [comment]
Hi @naseemkullah,

I would be happy to do that but I need to go through approval process with my organization before contributing with a PR and that would take some time.

It would be good if you can put this for me.

Also regarding use case : We are using Traefik with custom label selector and this Ingress is not getting picked up by Traefik due to missing label that we are attaching to all our Ingress Rules.

**Comment by NicolasLemince** [comment]
Hello @naseemkullah, 
Is there any step forward regarding this request ? I need this feature and it doesn't seem to be available. If not I can do a PR.

**Comment by naseemkullah** [comment]
Hi @NicolasLemince, a PR sounds good.
