### ISSUE TITLE
Create a config map object for a JSON file to be passed as the jaeger query UI configuration

### ISSUE THREAD

**Issue by mehta-ankit** [jaegertracing/helm-charts#118]
Based on https://www.jaegertracing.io/docs/1.18/frontend-ui/#configuration, It says a JSON file can be passed in as configuration.

Similar to how for Collector's strategy file [strategies.json](https://github.com/jaegertracing/helm-charts/blob/master/charts/jaeger/templates/collector-configmap.yaml) we can create a configmap template for the jaeger query UI  config JSON file . 

this would make it easy for users to pass in configuration in the values file.

I can add it in , since i already created a configMap for my own purposes.

**Comment by naseemkullah** [comment]
Sounds good @mehta-ankit, I'll be looking out for your PR then :) Thanks!

**Comment by mehta-ankit** [comment]
@naseemkullah closing this issue, since the PR merged.
