### ISSUE TITLE
[jaeger] increase env var flexibility

### ISSUE THREAD

**Issue by naseemkullah** [jaegertracing/helm-charts#120]
We should improve env var flexibility.

- change `env: {}` key value pairs to the more flexible `env: []` as-is yaml
  - see https://github.com/jaegertracing/helm-charts/pull/119 for more details

cc @pavelnikolov  @cgroschupp @mehta-ankit @Jasstkn  @arpitjindal97

**Comment by Jasstkn** [comment]
Hello @naseemkullah! Thanks for asking me, I really appreciate it.

Why we can't combine those approaches? 
Let's say all of the env variables will be changed in env: {}, but extraEnvConfig: using toYaml

**Comment by cgroschupp** [comment]
Hi @Jasstkn, only Values.esIndexCleaner.env and .Values.schema.env are affected. And I think env and extraEnvConfig are very confusing

**Comment by Jasstkn** [comment]
@cgroschupp if I understand correct, @naseemkullah wants to extend this change to all of the environment variables..

**Comment by naseemkullah** [comment]
Yeah to today, on top of es-index-cleaner and schema-job other components using `env: {}` as it is today are the any [storage related](https://github.com/jaegertracing/helm-charts/blob/6787ff09cec9d06290f999d5a5d3fb64edd6ba77/charts/jaeger/templates/_helpers.tpl#L318-L327) env var for all components (i.e. anything beginning with [`ES_`](https://github.com/jaegertracing/helm-charts/blob/6787ff09cec9d06290f999d5a5d3fb64edd6ba77/charts/jaeger/templates/_helpers.tpl#L312-L315) or [`CASSANDRA_`](https://github.com/jaegertracing/helm-charts/blob/6787ff09cec9d06290f999d5a5d3fb64edd6ba77/charts/jaeger/templates/_helpers.tpl#L287-L290)) ... I'd like to avoid breaking that, but I'd also like avoid having two ways to use `env:` in the various components of the charts. 


So while `extraEnvConfig` is verbose,  the idea is right and `extraEnv` could be a good way to introduce the improved way to add env vars.

`extraEnv` has proven to be a widely used var name as per grepping for it in the stable repo: https://github.com/helm/charts/search?p=1&q=extraEnv


Also, extraEnv is actually accurate since we are adding env vars to some others that are added by other means (thats to say, `env` sounds like it is authorative whereas `extraEnv` sounds additive)

@cgroschupp @Jasstkn and everyone else WDYT?

**Comment by naseemkullah** [comment]
Also, we could add alongside `env:` of the schema, es index cleaner and storage components `extraEnv` and add a notice in the notes that `env:` is deprecated in favor of `extraEnv` and in a few months, get rid of `env:`.

**Comment by mehta-ankit** [comment]
@naseemkullah
I feel having both `env` and `extraEnv` is confusing.

I have some questions  ?
1) READMe mentions `<component>.env` - `Additional environment variables` - `{}`.
but i don't see that value (`.Values.collector.env` or .Values.query.env) being used for other components, like query or collector. Can we not pass in environment variables for those right now?

2) If we use `env: {}` , How can we use `valueForm` approach to read from secrets or configMap objects in K8s ?? There are some [examples](https://opensource.com/article/19/6/introduction-kubernetes-secrets-and-configmaps) where its helpful:

**Comment by mehta-ankit** [comment]
I guess i was late to the party 😄 
 https://github.com/jaegertracing/helm-charts/pull/121 now.  👍

**Comment by arpitjindal97** [comment]
I agree with @naseemkullah , `extraEnv` is quite popular and understandable. 

Adding deprecation notice with end of support date will be sufficient.
