### ISSUE TITLE
Disabling Elasticsearch sniffing on the chart

### ISSUE THREAD

**Issue by otherview** [jaegertracing/helm-charts#122]
Hi 👋  !

I've been trying to disable sniffing for Elasticsearch, but no luck. 
Maybe I'm doing something wrong ?

I'm using 
```
collector:
    cmdlineParams:
      es.sniffer: "false"
```

Still I'm getting the `failed to create primary Elasticsearch client with health check timeout - no Elasticsearch node available`

From what I can tell this is related with using https://github.com/olivere/elastic . And because I'm using an AWS Elasticsearch theres an issue when it sniffs the available nodes.

Any help would be much appreciated ! :)

**Comment by naseemkullah** [comment]
Hi @otherview, according to https://www.jaegertracing.io/docs/1.18/cli/ it appears the `es.sniffer` defaults to `false`. Could you try omitting the config you've added?

If this does not work I'd suggest raising an issue with the jaeger code base itself.

**Comment by otherview** [comment]
Hi @naseemkullah !

Yes, I've tried without it too.. And the same problem :(

Raised a question there 👍  at https://github.com/jaegertracing/jaeger/issues/2291

**Comment by naseemkullah** [comment]
fwiw, i'm also afraid that the string "false" might be interpreted as truthy in the chart configuration. so best leave it out since the default is false imho

**Comment by naseemkullah** [comment]
Finally, I'd suggest removing any mention of the chart in the question, instead saying that jaeger should have es.sniffer as false by default and you are not getting expected behaviour, because if not the issue might be redirected here, creating an infinite loop :)

**Comment by otherview** [comment]
Fair point 😄

**Comment by otherview** [comment]
Figured this one out.

The error is the same but the issue was that it was using the default username and password set in https://github.com/jaegertracing/helm-charts/blob/fa4dac8d7705fad8a02733aa43019e14dab0b547/charts/jaeger/values.yaml#L51

So it threw me off on the wrong direction.

Thanks! Closing this one now 👍
