### ISSUE TITLE
[jaeger] Disk storage question

### ISSUE THREAD

**Issue by sergeyshaykhullin** [jaegertracing/helm-charts#125]
Can i use `jaegertracing/jaeger` helm chart with badger and pvc+pv like `jaegertracing/jaeger-operator` can create?

**Comment by naseemkullah** [comment]
Hi @sergeyshaykhullin , that is not possible with the current jaeger chart. I think badger is only for all-in-one correct? We could potentially create an `all-in-one` chart for the purpose.

**Comment by sergeyshaykhullin** [comment]
Yes, for all-in-one, i don't know could you create separate chart, because jaeger-operator has badger support
