### ISSUE TITLE
[jaeger-operator] jaeger-operator-metrics service shouldn't be created by the chart

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/helm-charts#126]
The `jaeger-operator-metrics` service seems to be [created by the Helm Chart](https://github.com/jaegertracing/helm-charts/blob/fa4dac8d7705fad8a02733aa43019e14dab0b547/charts/jaeger-operator/templates/service.yaml#L4), but it's actually created by the jaeger-operator [during its bootstrap](https://github.com/jaegertracing/jaeger-operator/blob/ec535126223c87c7358ef1dfb6c4af588d4e07b3/pkg/cmd/start/bootstrap.go#L355-L377). The service from the chart doesn't seem to be creating a properly configured service, as seen in a [recent thread](https://groups.google.com/d/msg/jaeger-tracing/CbiPL10p7Qo/r4F1Cx9RBwAJ) in the Jaeger mailing list.

**Comment by naseemkullah** [comment]
cc @cpanato @batazor

**Comment by scott-dang91** [comment]
any update?
