### ISSUE TITLE
[jaeger-operator] Service monitor errors

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/helm-charts#141]
We received two reports in the Jaeger Operator project which seems to indicate a bug in how the Helm Charts are provisioning the service monitor resources. See: https://github.com/jaegertracing/jaeger-operator/issues/1067 and https://github.com/jaegertracing/jaeger-operator/issues/1114.

**Comment by naseemkullah** [comment]
cc @cpanato @batazor can you please have a look?

**Comment by scott-dang91** [comment]
any update?
