### ISSUE TITLE
[jaeger] Kafka pod keep restarting because of SIGTERM signal

### ISSUE THREAD

**Issue by mehta-ankit** [jaegertracing/helm-charts#149]
Using Latest version of the chart `0.36.0`, and installing it with ingester `enabled`  and with new kafka cluster.

Zookeeper pods start up normally, but kafka pod keeps shutting down because of a SIGTERM signal as seen in the logs.

Before the SIGTERM signal:
![image](https://user-images.githubusercontent.com/22157398/92812737-d522fe00-f38d-11ea-84e2-1a2e0749c65f.png)

After the SIGTERM signal
![image](https://user-images.githubusercontent.com/22157398/92812717-cc322c80-f38d-11ea-8f75-a9d742abc34a.png)

Based on the README, there shouldn't be anything else needed to run this setup with this chart.

Any ideas why Kafka is failing to come up.

**Comment by mehta-ankit** [comment]
I had to tweak liveness and readiness probe values, and kafka pods (3 in my case because of replica value being 3) were able to come up and go into ready state.

**Comment by mehta-ankit** [comment]
@naseemkullah have you tried to use the kafka chart that our helm chart points to ?
I am still concerned because even after the pods were up, they kept failing the liveness probe.
I checked kafka chart uses `jps` as a liveness probe check. I tried running jps by doing exec on the pod, but it returns nothing, even when a java process is up and running.

I checked bitnami's Kafka chart does not use jps but instead uses tcp-socket: https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/statefulset.yaml#L298

Also i found this bug, https://bugs.openjdk.java.net/browse/JDK-8193710.
Which i think can maybe mess up the liveness probe.

SO i wanted to check if others have used this kafka chart and can confirm it works fine.

**Comment by naseemkullah** [comment]
Hey @mehta-ankit, thanks for raising this. I have never personally installed the Kafka component. Seeing that the incubator repo is deprecated we should try another Kafka chart as a dependency. Maybe the bitnami one would be better?

**Comment by naseemkullah** [comment]
I though confluence charts would be a good idea initially https://github.com/confluentinc/cp-helm-charts/issues/374 but no response

**Comment by mehta-ankit** [comment]
> Hey @mehta-ankit, thanks for raising this. I have never personally installed the Kafka component. Seeing that the incubator repo is deprecated we should try another Kafka chart as a dependency. Maybe the bitnami one would be better?

I can give bitnami chart a try and update the issue. 

Till that time I would like to keep the issue open. 

Thanks

**Comment by naseemkullah** [comment]
Worth mentioning @arpitjindal97 added this feature and may have additional knowledge about Kafka configuration

**Comment by arpitjindal97** [comment]
@mehta-ankit When I created this feature, it worked fine out of the box. I'm not able to figure out any issue in configuration apart from `jps`.

You can try few things:
 - Try to use an upgraded version of Kafka Helm Chart. See [here](https://kubernetes-charts-incubator.storage.googleapis.com/)
 - If still it doesn't work then try Bitnami's chart

**Comment by arpitjindal97** [comment]
Also, if Bitnami's chart works for you, you can try to contribute back the fix to Helm incubator Kafka Chart

**Comment by mehta-ankit** [comment]
@arpitjindal97 
Yea i was thinking of giving the latest incubator kafka chart a try.

We use this value `^0.20.6` in jaeger's requirement.yaml file, and i assumed this would mean it would not pull `0.21.2` version of the chart (which is the latest)
But when i am running `helm dep update` the jaeger chart  tgz (v0.36.0) that gets created contains Kafka chart with version `0.21.2`.
According to this definition: https://github.com/Masterminds/semver#caret-range-comparisons-major
it should only be getting a version `>=0.20.6 and <0.21.0`. I am confused 😕

**Comment by arpitjindal97** [comment]
Try to use use hard coded version of Kafka Chart i.e `0.20.6` 

If it works, then upgrade each version one by one and see where `jps` is giving problems

**Comment by naseemkullah** [comment]
> @arpitjindal97
> Yea i was thinking of giving the latest incubator kafka chart a try.
> 
> We use this value `^0.20.6` in jaeger's requirement.yaml file, and i assumed this would mean it would not pull `0.21.2` version of the chart (which is the latest)
> But when i am running `helm dep update` the jaeger chart tgz (v0.36.0) that gets created contains Kafka chart with version `0.21.2`.
> According to this definition: https://github.com/Masterminds/semver#caret-range-comparisons-major
> it should only be getting a version `>=0.20.6 and <0.21.0`. I am confused 😕

So `^0.20.6` means it would not go to `1.x.x` but minor upgrades are permitted (i.e. to `0.21.x`), generally minor versions should not be breaking, but often before 1.x.x has been released they can be.

**Comment by mehta-ankit** [comment]
Thanks for the info @naseemkullah .
My confusion came from the documentation in the link i shared above: 
https://github.com/Masterminds/semver#caret-range-comparisons-major
which gives this as example: `0.2.3 is equivalent to >=0.2.3 <0.3.0`

**Comment by naseemkullah** [comment]
> Thanks for the info @naseemkullah .
> My confusion came from the documentation in the link i shared above:
> https://github.com/Masterminds/semver#caret-range-comparisons-major
> which gives this as example: `0.2.3 is equivalent to >=0.2.3 <0.3.0`

That is pretty confusing indeed. As per https://helm.sh/docs/topics/charts/#the-kubeversion-field

> Apart from version constrains employing operators = != > < >= <= the following shorthand notations are supported

> hyphen ranges for closed intervals, where 1.1 - 2.3.4 is equivalent to >= 1.1 <= 2.3.4.
> wildcards x, X and *, where 1.2.x is equivalent to >= 1.2.0 < 1.3.0.
> tilde ranges (patch version changes allowed), where ~1.2.3 is equivalent to >= 1.2.3 < 1.3.0.
> caret ranges (minor version changes allowed), where ^1.2.3 is equivalent to >= 1.2.3 < 2.0.0.

**Comment by mehta-ankit** [comment]
> > Thanks for the info @naseemkullah .
> > My confusion came from the documentation in the link i shared above:
> > https://github.com/Masterminds/semver#caret-range-comparisons-major
> > which gives this as example: `0.2.3 is equivalent to >=0.2.3 <0.3.0`
> 
> That is pretty confusing indeed. As per https://helm.sh/docs/topics/charts/#the-kubeversion-field

I agree 😢 
> 
> > Apart from version constrains employing operators = != > < >= <= the following shorthand notations are supported
> 
> > hyphen ranges for closed intervals, where 1.1 - 2.3.4 is equivalent to >= 1.1 <= 2.3.4.
> > wildcards x, X and *, where 1.2.x is equivalent to >= 1.2.0 < 1.3.0.
> > tilde ranges (patch version changes allowed), where ~1.2.3 is equivalent to >= 1.2.3 < 1.3.0.
> > caret ranges (minor version changes allowed), where ^1.2.3 is equivalent to >= 1.2.3 < 2.0.0.

But then for detailed description they tell you to go to the same link 😆 
![image](https://user-images.githubusercontent.com/22157398/93095922-bc5a6700-f671-11ea-974b-6235b0601f0b.png)

**Comment by naseemkullah** [comment]
> > > Thanks for the info @naseemkullah .
> > > My confusion came from the documentation in the link i shared above:
> > > https://github.com/Masterminds/semver#caret-range-comparisons-major
> > > which gives this as example: `0.2.3 is equivalent to >=0.2.3 <0.3.0`
> > 
> > 
> > That is pretty confusing indeed. As per https://helm.sh/docs/topics/charts/#the-kubeversion-field
> 
> I agree 😢
> 
> > > Apart from version constrains employing operators = != > < >= <= the following shorthand notations are supported
> > 
> > 
> > > hyphen ranges for closed intervals, where 1.1 - 2.3.4 is equivalent to >= 1.1 <= 2.3.4.
> > > wildcards x, X and *, where 1.2.x is equivalent to >= 1.2.0 < 1.3.0.
> > > tilde ranges (patch version changes allowed), where ~1.2.3 is equivalent to >= 1.2.3 < 1.3.0.
> > > caret ranges (minor version changes allowed), where ^1.2.3 is equivalent to >= 1.2.3 < 2.0.0.
> 
> But then for detailed description they tell you to go to the same link 😆
> ![image](https://user-images.githubusercontent.com/22157398/93095922-bc5a6700-f671-11ea-974b-6235b0601f0b.png)

Actually they describe it correctly: https://github.com/Masterminds/semver#tilde-range-comparisons-patch

**Comment by arpitjindal97** [comment]
<img src="https://user-images.githubusercontent.com/15676216/93096246-c7d57e80-f6c1-11ea-99be-6d6ec3cef970.png" alt="Mind about to blast" width="300"/>

**Comment by mehta-ankit** [comment]
> https://github.com/Masterminds/semver#tilde-range-comparisons-patch

that explanation is  for the tilda `~` not caret `^` that we use . 😆

**Comment by naseemkullah** [comment]
> > https://github.com/Masterminds/semver#tilde-range-comparisons-patch
> 
> that explanation is for the tilda `~` not caret `^` that we use . 😆

Just below is tilda :) I linked that fragment so you can see both

**Comment by mehta-ankit** [comment]
@arpitjindal97 @naseemkullah 
Could my problem be because i did not set `.values.topics` for kafka chart 
https://github.com/helm/charts/blob/776c38ddec573bcc6d6e9cd421e51689d7aa50f3/incubator/kafka/templates/configmap-config.yaml#L1
without it, configmap would not be created.

I know we set topic, but that is for the collector: https://github.com/jaegertracing/helm-charts/blob/master/charts/jaeger/values.yaml#L74

**Comment by arpitjindal97** [comment]
Topic needs to be set without it Kafka will not work in any scenario

**Comment by mehta-ankit** [comment]
> Topic needs to be set without it Kafka will not work in any scenario

i thought so, but without setting it directly as a value on kafka chart, i was seeing logs like this on kafka pod:
```
[2020-09-14 14:03:09,209] INFO [Log partition=jaeger_v1_test-0, dir=/var/lib/kafka/logs] Loading producer state till offset 46 with message format version 2 (kafka.log.Log)
[2020-09-14 14:03:09,247] INFO [ProducerStateManager partition=jaeger_v1_test-0] Loading producer state from snapshot file '/var/lib/kafka/logs/jaeger_v1_test-0/00000000000000000046.snapshot' (kafka.log.ProducerStateManager)
```
So i assumed it picked up the topic from the producer (jaeger collector in this case).

Also, i am new to kafka , so do not know everything about it.

**Comment by arpitjindal97** [comment]
If kafka topic is set, then you can try running it with Hardcoded version with Kafka. Also, share the `values.yaml` you are using. I will see if I can spin up a Cluster and deploy the setup.

**Comment by mehta-ankit** [comment]
these are the values for kafka i am passing in.

```
kafka:
    imageTag: "5.5.1"
    # topics:
    #   - name: jaeger_v1_test
    #     replicationFactor: 1
    replicas: 1
    zookeeper:
      replicaCount: 1
      persistence:
        enabled: true
        size: "2Gi"
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
    # This is all crazy - Commits lost, repo's deprecated etc.
    # Look at the following.
    # https://github.com/confluentinc/cp-docker-images/issues/653
    # https://github.com/confluentinc/cp-docker-images/pull/184#issuecomment-359464513
    persistence:
      mountPath: "/var/lib/kafka"
    readinessProbe:
      periodSeconds: 45
      timeoutSeconds: 45
      initialDelaySeconds: 120
      failureThreshold: 6
    livenessProbe:
      periodSeconds: 45
      timeoutSeconds: 45
      initialDelaySeconds: 120
      failureThreshold: 6
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
```
Up until now i was using these values without the commented lines.
The commented 3 lines i have just added after my comment above.

**Comment by arpitjindal97** [comment]
By the time, I will check and deploy the setup. You can also look at this repo: https://github.com/arpitjindal97/jaeger-deployer

I developed a simple tool few months back which makes the deployment cycle easier

**Comment by mehta-ankit** [comment]
I have tried kafka chart version `0.26.0` and it has the same problem for me. The kafka pod keeps restarting with liveness probe failed message.

I was not able to try it with setting the value for `topics` in kafka chart.
This was because that chart does not have an option to set securityContext for the job that creates the pod: https://github.com/helm/charts/blob/776c38ddec573bcc6d6e9cd421e51689d7aa50f3/incubator/kafka/templates/job-config.yaml as i mentioned in one of my comments above.
Trying to work around it, to see if that is the issue.

**Comment by mehta-ankit** [comment]
@naseemkullah @arpitjindal97 i did a test to confirm, if liveness probe was the problem and if JPS bug i found was the underlying issue.

I replaced liveness probe for the statefulset with `ps -aux` instead of `jps`
`Liveness:   exec [sh -ec ps -aux | /bin/grep SupportedKafka]`
and pod is stable now. Not failing the livenessprobe and not being restarted by K8s.

is it worth the has·sle getting this fix in to the incubator chart ???
