### ISSUE TITLE
[jaeger-operator] Cannot set log-level via helm chart

### ISSUE THREAD

**Issue by ssdowdavalon** [jaegertracing/helm-charts#165]
The default log level does not provide useful output for diagnosing problems with jaeger deployments.  The helm chart does not provide a way to set the `--log-level` command line parameter to increase operator log output.

**Comment by yury-kozlov** [comment]
Will be a useful feature!
As a workaround I unzip the chart and manually adjust the deployment.yaml:
```
          env:
            - name: LOG-LEVEL
              value: debug
```

**Comment by Liubey** [comment]
@yury-kozlov @ssdowdavalon Hi, can I replenish it. In helm chart "jaeger", I set it like this:
<img width="433" alt="image" src="https://github.com/jaegertracing/helm-charts/assets/5568302/497a7a30-d437-4f68-a19e-104a36685982">
But I got:
<img width="1486" alt="image" src="https://github.com/jaegertracing/helm-charts/assets/5568302/ae145503-aa7c-4544-871b-c158f0f8c83b">
Is something wrong?
Thank you.

**Comment by yury-kozlov** [comment]
@Liubey I haven't been using jaeger charts for a long time, but it might be possible that `LOG-LEVEL` variable is applied only to the operator itself (and not to individual components like jaeger collector).
