### ISSUE TITLE
[jaeger] Image tag for es-index cleaner , rollover and lookup cronjobs should be " .Values.tag"

### ISSUE THREAD

**Issue by mehta-ankit** [jaegertracing/helm-charts#185]
In all other jaeger resources image tag  used is `{{ .Values.tag }}`, which moves with Jaeger version released.
All ES index cronjob resources like cleaner, rollover and lookup use their own values for tags. 
This makes it inconsistent with other image versions.

It's not a critical issue, but a quality of life improvement. We just have to modify the cronjob yaml files to use the image name tag like others
`{{ .Values.esIndexCleaner.image }}:{{ .Values.esIndexCleaner.tag }}"` **would become** `{{ .Values.esIndexCleaner.image }}:{{ .Values.tag }}"`

Only issue i am thinking about is backwards compatibility. 🤔

**Comment by mehta-ankit** [comment]
@naseemkullah thoughts ?

**Comment by naseemkullah** [comment]
Good point @mehta-ankit , I would go a step further and make the tag of all jaeger components default to the chart's appVersion as per:

- https://github.com/helm/helm/blob/b30f61d76de3805a839a95dc0f8ef8d8e208b09f/pkg/chartutil/create.go#L292
- https://github.com/helm/helm/blob/b30f61d76de3805a839a95dc0f8ef8d8e208b09f/pkg/chartutil/create.go#L115-L116
