### ISSUE TITLE
[jaeger-operator] Chart version 2.18.1 incompatible with Kubernetes versions <1.16

### ISSUE THREAD

**Issue by OmriHarary** [jaegertracing/helm-charts#187]
`apiextensions.k8s.io/v1` has only been available since Kubernetes 1.16, which means that the change introduced by #186 and published in version 2.18.1 of the chart broke compatibility with all earlier Kubernetes releases. The chart README says that the version requirement is 1.8+.

The [CRD in jaeger-operator itself](https://github.com/jaegertracing/jaeger-operator/blob/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml#L1) still uses `apiextensions.k8s.io/v1beta1`, which is still  available as recently as Kubernetes 1.20.

**Comment by batazor** [comment]
@OmriHarary We can update the k8s version in the readme

**Comment by OmriHarary** [comment]
@batazor That's fine, as long as it's documented.

Personally, though, I'm not sure if the change was really that necessary, and I don't think it makes sense to drop support for so many versions in a patch release.
