### ISSUE TITLE
[jaeger] all-in-one strategy

### ISSUE THREAD

**Issue by jjangga0214** [jaegertracing/helm-charts#192]
Hi!

I am evaluating `jaeger` chart (not `jaeger-operator`) for a production environment, with elasticsearch.

However, on a local development environment(e.g. minikube, microk8s, kind, k3d), elasticsearch(or Cassandra) is too heavy. 
So, I want to use the `all-in-one` strategy *just by replacing a few values* from the `jaeger` chart, but not by changing the entire chart to `jaeger-operator`.

IMHO, it would be convenient for some cases.

How do you think?

**Comment by denniseffing** [comment]
+1

**Comment by naseemkullah** [comment]
This would be great.

Is anyone up for a PR?

The idea would be that we would have in values.yaml:

```yaml
allInOne:
  enabled: false
```

if `allInOne.enabled` it would deploy the allInOne deployment, service, serviceAccount and ingress.

It could potentially be a sub-chart

**Comment by denniseffing** [comment]
@naseemkullah I opened up a pull request implementing your idea. Let me know what you think. :)
