### ISSUE TITLE
Add support for all-in-memory storage backend

### ISSUE THREAD

**Issue by bravecobra** [jaegertracing/helm-charts#199]
It'd be nice to have support for an in-memory backend as specified here:
https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/all-in-one/jaeger-all-in-one-template.yml

You'd be able to fire up a jaeger ui for dev purposes on your dev machine easily.

**Comment by naseemkullah** [comment]
Agreed, there is already an issue open: https://github.com/jaegertracing/helm-charts/issues/192

Can this one be closed in favour of the above?

**Comment by bravecobra** [comment]
Closing in favor of #192
