### ISSUE TITLE
[jaeger] jaeger-elasticsearch secret deleted on upgrade but not recreated

### ISSUE THREAD

**Issue by mehta-ankit** [jaegertracing/helm-charts#204]
I upgraded the chart from 0.39.6 to latest version and it broke for me.
As far as i can see the my ingester and query pods were not coming up giving this error:

```
Error: secret "jaeger-elasticsearch" not found
```
I think this is related to this change : https://github.com/jaegertracing/helm-charts/pull/189

- When i upgraded my current release (with new version of the chart), i saw secret was deleted but never got created again and as mentioned above ingester and query pods were not able to find it.
- When i installed the chart as a new helm release, it worked fine.

on another note, i do not use esRollover and hence i feel, if this change was only needed to make sure esRollover-init hook can find this secret, we should have made the annotations conditional instead of adding them by default for everyone.

@grassiale Can you weigh on this please ?
Maybe help me understand why this is doing what it is doing ?

**Comment by grassiale** [comment]
Hi @mehta-ankit, so you started from version 0.39.6, and with no changes to values the secret was removed. I was absolutely not expecting that to happen considering the helm lifecycle. Especially with a resource policy of keep as specified.
II have to investigate it a little. 
By the way, you are correct in assuming that if you don't use the job hook, than the secret does not need to be created as a hook.

**Comment by grassiale** [comment]
Hi @mehta-ankit I've just tried to upgrade from 0.39.6, performing a diff showed me that the annotations would have been added to the secret:
```
+   annotations:
+     "helm.sh/hook": pre-install,pre-upgrade
+     "helm.sh/hook-weight": "-1"
+     "helm.sh/hook-delete-policy": before-hook-creation
+     "helm.sh/resource-policy": keep
```
And right after, with an apply, everything went smoothly, the secret was deleted and recreated because of the `before-hook-creation` policy. But nothing broke. Can you tell me your helm version?

**Comment by mehta-ankit** [comment]
Here is the version : 
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```
Can you tell me how did u run helm upgrade.
The way our code was doing it was 
```
helm upgrade --install "release-X" <some_chart_path> \
    --namespace "namespace" \
    --debug --reset-values --atomic \
    --wait --timeout 1200s \
    --values values.yaml \
    --values env-values.yaml \
```

**Comment by grassiale** [comment]
I have tried to run this command in my current environment, that has helm v2.16.3, and it is working all right, recreating the secret right after deleting it and all.
```
helm secrets upgrade --install jaeger-test-store jaegertracing/jaeger \
    --namespace "jaeger-test" \
    --debug --reset-values --atomic \
    --values k8s/test/helm-values/jaeger-store.yaml --values k8s/test/helm-values/jaeger-store.secret.yaml
```

Will try soon on an helm3 env with no secrets.

**Comment by grassiale** [comment]
Hi @mehta-ankit I've tried to reproduce the issue with an helm v3.5.2 environment.
But still no luck: the secrets gets deleted and recreated in no time, and pods are never lamenting it's absence.

**Comment by mehta-ankit** [comment]
@grassiale thank you for investigating this 🙏🏽 . I feel we can close this issue based on your test and since there is a workaround as well. I had to delete my release and re-deploy as mentioned in my comment above. We can re-open a new Issue , if anyone else finds the same problem.
