### ISSUE TITLE
rename mainline branch to main

### ISSUE THREAD

**Issue by naseemkullah** [jaegertracing/helm-charts#210]
more info: https://github.com/github/renaming

**Comment by yurishkuro** [comment]
renamed. Please make sure to update CI & badges as necessary

**Comment by naseemkullah** [comment]
Thanks @yurishkuro, will follow up with any mentions of master shortly

**Comment by naseemkullah** [comment]
https://github.com/jaegertracing/helm-charts/commit/d0856788497327fa935515495f876fdd1035cd59 covers the rest ✅
