### ISSUE TITLE
[Spark cronjob] Add jobAnnotations to Template

### ISSUE THREAD

**Issue by ichasco-heytrade** [jaegertracing/helm-charts#222]
Hi,

Could you add `jobAnnotations` to spark template? When jobs are used with istio or with vault-webhook it is needed to add some annotations. And the annotations in this case are only for the cronjob, not for the job.

Thanks :)

**Comment by mehta-ankit** [comment]
If i understand this correctly, it should just be a matter of adding `annotations` under metadata for the JobTemplate here: https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/spark-cronjob.yaml#L24

We would be happy to take a contribution @ichasco-heytrade
