### ISSUE TITLE
[jaeger] missing namespace when assigning ElasticSearch host

### ISSUE THREAD

**Issue by chinltong** [jaegertracing/helm-charts#24]
Installing `jaeger` helm chart into a customized namespace `tracing` using this helm command, that creates elasticsearch as well. 
```
helm upgrade --install jaeger jaegertracing/jaeger \
--set hotrod.enabled=true \
--set provisionDataStore.cassandra=false  \
--set provisionDataStore.elasticsearch=true \
--set storage.type=elasticsearch \
--set collector.service.zipkinPort=9411 \
-n tracing --debug
```
The jaeger-collector deployment assigns `jaeger-elasticsearch-client` as the host
```       
        - name: ES_SERVER_URLS
          value: http://jaeger-elasticsearch-client:9200
```
but it is not reachable because the ElasticSearch client is created in `tracing` namespace. 

It should be:
```
        - name: ES_SERVER_URLS
          value: http://jaeger-elasticsearch-client.tracing:9200
```

**Comment by naseemkullah** [comment]
Hi @chinltong, if both apps are intalled in the same `tracing` namespace, there should be no need to specify it, maybe something else is at play here.

What's the output of `kubectl get services -n tracing` ? is there a `jaeger-elasticsearch-client` service?

**Comment by chinltong** [comment]
> Hi @chinltong, if both apps are intalled in the same `tracing` namespace, there should be no need to specify it, maybe something else is at play here.
> 
> What's the output of `kubectl get services -n tracing` ? is there a `jaeger-elasticsearch-client` service?

@naseemkullah I also thought there is no need to specify the namespace. but it didn't work because the elastic search host is not reachable in `jaeger-collector` logs therefore I changed it manually. 

output is:
```
NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                  AGE
jaeger-agent                     ClusterIP   172.20.129.152   <none>        5775/UDP,6831/UDP,6832/UDP,5778/TCP      8d
jaeger-collector                 ClusterIP   172.20.16.39     <none>        14250/TCP,14267/TCP,14268/TCP,9411/TCP   8d
jaeger-elasticsearch-client      ClusterIP   172.20.77.99     <none>        9200/TCP                                 21h
jaeger-elasticsearch-discovery   ClusterIP   None             <none>        9300/TCP                                 21h
jaeger-hotrod                    ClusterIP   172.20.190.90    <none>        80/TCP                                   8d
jaeger-query                     ClusterIP   172.20.4.68      <none>        80/TCP                                   8d
```

**Comment by naseemkullah** [comment]
Was collector crashing on repeat when it could not reach ES?

**Comment by naseemkullah** [comment]
Do you mind changing the value back to:

```
        - name: ES_SERVER_URLS
          value: http://jaeger-elasticsearch-client:9200
```

and trying again?

**Comment by chinltong** [comment]
> Do you mind changing the value back to:
> 
> ```
>         - name: ES_SERVER_URLS
>           value: http://jaeger-elasticsearch-client:9200
> ```
> 
> and trying again?

yes, I did and worked.   maybe first time it failed because the ElasticSearch did not come up completely. 

I am closing this issue.

**Comment by cristianoveiga** [comment]
> > Do you mind changing the value back to:
> > ```
> >         - name: ES_SERVER_URLS
> >           value: http://jaeger-elasticsearch-client:9200
> > ```
> > 
> > 
> > and trying again?
> 
> yes, I did and worked. maybe first time it failed because the ElasticSearch did not come up completely.
> 
> I am closing this issue.



> > Hi @chinltong, if both apps are intalled in the same `tracing` namespace, there should be no need to specify it, maybe something else is at play here.
> > What's the output of `kubectl get services -n tracing` ? is there a `jaeger-elasticsearch-client` service?
> 
> @naseemkullah I also thought there is no need to specify the namespace. but it didn't work because the elastic search host is not reachable in `jaeger-collector` logs therefore I changed it manually.
> 
> output is:
> 
> ```
> NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                  AGE
> jaeger-agent                     ClusterIP   172.20.129.152   <none>        5775/UDP,6831/UDP,6832/UDP,5778/TCP      8d
> jaeger-collector                 ClusterIP   172.20.16.39     <none>        14250/TCP,14267/TCP,14268/TCP,9411/TCP   8d
> jaeger-elasticsearch-client      ClusterIP   172.20.77.99     <none>        9200/TCP                                 21h
> jaeger-elasticsearch-discovery   ClusterIP   None             <none>        9300/TCP                                 21h
> jaeger-hotrod                    ClusterIP   172.20.190.90    <none>        80/TCP                                   8d
> jaeger-query                     ClusterIP   172.20.4.68      <none>        80/TCP                                   8d
> ```

Hey @chinltong ,

I'm getting a similar error...

In my installation, I only have the elasticsearch-master and elasticsearch-master-headless services (the "jaeger-elasticsearch-client" is missing).

Maybe there is something elasticsearch subchart  that we should be overriding to get exactly the same configuration expected by the jager chart? Can you tell what am I missing?

Cristiano
