### ISSUE TITLE
[CI] Release is failing

### ISSUE THREAD

**Issue by naseemkullah** [jaegertracing/helm-charts#25]
```
Error: error creating GitHub release: POST https://api.github.com/repos/jaegertracing/helm-charts/releases: 404 Not Found []
```

We can begin by reverting the token used to see if that caused the issue.

**Comment by jpkrohling** [comment]
Could you try again? Looks like the user didn't have permission to this repo.

**Comment by naseemkullah** [comment]
It works now. Thanks @jpkrohling!
