### ISSUE TITLE
Deploying with ingress fails

### ISSUE THREAD

**Issue by cwrau** [jaegertracing/helm-charts#277]
**Describe the bug**
Since Helm Chart commit ac557aa198d50910b6c4f71f76a54d60de26d63c the deployment fails for us, as we don't have `networking.k8s.io/v1/Ingress` but we do have `networking.k8s.io/v1/NetworkPolicy`.

**To Reproduce**
1. Have a cluster without `networking.k8s.io/v1/Ingress` but with something else in apiVersion `networking.k8s.io/v1`, e.g. `NetworkPolicy`
2. Try to deploy with ingress enabled
3. See error message

**Expected behavior**
Either a better check, which I don't think is possible with Helm?, or an additional flag whether to use `networking.k8s.io/v1` for the ingress

**Screenshots**

**Version (please complete the following information):**
 - OS: N.A.
 - Jaeger version: N.A.
 - Deployment: Kubernetes
 - Kubernetes Version: v1.18.8
 - Helm Chart version: 0.46.5

**What troubleshooting steps did you try?**
I looked through the source to find a toggle or something like that

**Additional context**
Log;

```log
installation failed: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
```

**Comment by mehta-ankit** [comment]
😢 

@cwrau Don't you think a specific check like this would work ?? Looking at the docs for Helm , it seems like it should work: 
![image](https://user-images.githubusercontent.com/22157398/129748864-56d33aa6-ca06-421d-9fc3-52e23ca38cc8.png)

```
{{- $useNetworkingV1 := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
```

**Comment by cwrau** [comment]
Yes, you're right!!! I didn't know about that! I only ever saw this used with the apiVersions, not with the specific resource (should've looked at the docs 🙈)

Yes, that should work then, and I also learned something new 👍️

**Comment by naseemkullah** [comment]
we may want to factor out the apiVersion into helpers.tpl as done [here](https://github.com/helm/charts/blob/7e45e678e39b88590fe877f159516f85f3fd3f38/incubator/vault/templates/_helpers.tpl#L67-L76)

**Comment by cwrau** [comment]
I can recommend using https://github.com/bitnami/charts/tree/master/bitnami/common

They pretty much standardize everything, including things like apiVersion for Ingress, the different backend for `v1` and `v1beta1`

We've been using the common chart in all our charts for a long time now 👍️

**Comment by naseemkullah** [comment]
> I can recommend using https://github.com/bitnami/charts/tree/master/bitnami/common
> 
> They pretty much standardize everything, including things like apiVersion for Ingress, the different backend for `v1` and `v1beta1`
> 
> We've been using the common chart in all our charts for a long time now 👍️

That's a good idea! Happy to review a PR
