### ISSUE TITLE
[jaeger-operator] Sync the CRD for 1.17

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/helm-charts#28]
Based on #20, this issue is a heads-up that the CRD file has been changed in the Operator's master and will be released as part of 1.17. 

https://github.com/jaegertracing/jaeger-operator/pull/819

**Comment by bsundsrud** [comment]
I would like to bump this for 1.18 as well, just ran into a bunch of errors after deploying the operator and an instance like the following:
```
time="2020-07-08T10:16:25Z" level=error msg="failed to store the running status into the current CustomResource" error="jaegers.jaegertracing.io \"jaeger-instance\" not found" execution="2020-07-08 10:16:25.341972774 +0000 UTC" instance=jaeger-instance namespace=observability
```
And found out I needed to apply the CRD that matched the version, and I assumed that the operator chart had taken care of that.

**Comment by naseemkullah** [comment]
cc @cpanato @batazor
