### ISSUE TITLE
[Jaeger]Have resource limits for query agent sidecar

### ISSUE THREAD

**Issue by bhiravabhatla** [jaegertracing/helm-charts#282]
**Describe the bug**
As of now there is no way to configure resource limits for agent sidecar in query deployment. 

**Expected behavior**
Need to have a provision to configure resource limits for agent sidecar

**Additional context**
Not providing resource limits is being flagged as a runtime vulnerability by security scan tools.

**Comment by mehta-ankit** [comment]
This was fixed by https://github.com/jaegertracing/helm-charts/pull/283
