### ISSUE TITLE
No ability to specify externalTrafficPolicy in jaeger helm chart

### ISSUE THREAD

**Issue by shxdxwraze** [jaegertracing/helm-charts#285]
## Proposal - what do you suggest to solve the problem or improve the existing situation?

Ability to specify `externalTrafficPolicy ` through helm values.yml for all Jaeger components svc.

**Comment by mehta-ankit** [comment]
Trying to understand the use case:
I am assuming you want to set the the value for `externalTrafficPolicy` to `Local` as `cluster` is default.  And you have a use case to do this for all Jaeger components ?

**Comment by Shadowraze228** [comment]
Not for all, but anyway would be good if all fields customizable.

**Comment by mehta-ankit** [comment]
@Shadowraze228 We are happy to take a contribution, if you can make a PR.  Let's keep default `cluster` and if someone passes a value then overwrite it.
