### ISSUE TITLE
[jaeger] Add support to setup init container for jaeger-agent pods

### ISSUE THREAD

**Issue by mehta-ankit** [jaegertracing/helm-charts#286]
## Requirement - what kind of business use case are you trying to solve?

We have a use case to dynamically figure out some tags that we want to apply as agent level tags.
![image](https://user-images.githubusercontent.com/22157398/134915746-5f97e680-c42b-430c-bd19-fe846bb605d3.png)

To do that are trying to get some information from nodes and other places, and then patching the agent pod itself, and then using downward api to set environment variables with those values. Once we do this, we can set agent level tags to use thos env variables.

## Problem - what in Jaeger blocks you from solving the requirement?

This above mentioned use case and solution does not work, if we use a pod that runs a python script for example to do the above (patch the pod). Because by the time we do that, agent container has already started and cannot make use of the environment variables we wold create using downward api.

Using init-containers does solve the issue, because we run the same python script to patch our pod from init container and then set the value on env variables. Now by the time agent container starts the env variable is set and agent level tags can make use of them.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Allow the chart to pass in init container for agent daemonset yaml. Something like this:
```
{{- if or (.Values.agent.extraInitContainers)  }}
      {{ toYaml .Values.extraInitContainers | indent 6 }}
{{- end }}
```
and Values.yaml can have default value as empty:
```
agent:
   extraInitContainers: []
```

**Comment by mehta-ankit** [comment]
@naseemkullah 
my team can make a contribution to add this on the chart but I have an open question :
`Do we want this capability for all components or having it for agents for now is good enough ?`

**Comment by naseemkullah** [comment]
Hi @mehta-ankit , I think it is fine to have it in just agents for now... though while on the topic to configure all components with a common thing, the otel collector helm chart does something cool: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/a326feb2c59813c6133c9d060717e38a09cbf5f7/charts/opentelemetry-collector/values.yaml#L70-L71

We should probably do an overhaul of the chart at some point if we could incorporate that.

**Comment by mehta-ankit** [comment]
@naseemkullah If i understand it correctly, values below line 70 like `podSecurityContext` are applied to both daemonset and deployment collector because they are being used to create a template var: `opentelemetry-collector.pod` here: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/ba174548f6f07db9fcc843de46151beb0470590b/charts/opentelemetry-collector/templates/_pod.tpl#L1 and then used in both places. Right ?

**Comment by naseemkullah** [comment]
> @naseemkullah If i understand it correctly, values below line 70 like `podSecurityContext` are applied to both daemonset and deployment collector because they are being used to create a template var: `opentelemetry-collector.pod` here: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/ba174548f6f07db9fcc843de46151beb0470590b/charts/opentelemetry-collector/templates/_pod.tpl#L1 and then used in both places. Right ?

That seems right, the beauty is that they are also overridable for each individual component thanks to this trickery: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/ba174548f6f07db9fcc843de46151beb0470590b/charts/opentelemetry-collector/templates/deployment.yaml#L26-L29
