### ISSUE TITLE
Jaeger Operator CRD does not work as expected

### ISSUE THREAD

**Issue by yasinahlatci** [jaegertracing/helm-charts#289]
**Describe the bug**
Hi, We use Jaeger-operator-2.24.0 helm chart. The crd is not compatible with the chart. When we install, Jaeger pod and service and etc. is up and running but we are not be able to see status: Running, it is coming null ( empty string )

**To Reproduce**
1. helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
2. helm install --name my-release jaegertracing/jaeger-operator

**Expected behavior**
```
kubectl get jaegers
NAMESPACE   NAME                         STATUS    VERSION   STRATEGY   STORAGE   AGE
default      my-release-operator-jaeger   Running   1.24.0    allinone   memory    15m
```
**Version (please complete the following information):**
 - OS: Linux amazon ami
 - Jaeger version: 1.24.0
 - Deployment: Kubernetes on EKS

**What troubleshooting steps did you try?**
I cloned the chart and change the crd.yaml with latest one. 
Link: [https://raw.githubusercontent.com/jaegertracing/jaeger-operator/master/deploy/crds/jaegertracing.io_jaegers_crd.yaml](url)
Then it works as expected

**Comment by tiagolobocastro** [comment]
I've raised #288 to address this
