### ISSUE TITLE
Support batch/v1 for CronJob resources

### ISSUE THREAD

**Issue by maristgeek** [jaegertracing/helm-charts#356]
## Requirement - what kind of business use case are you trying to solve?

The `batch/v1beta1` API will no longer be served by the API starting in the 1.25 release of Kubernetes, supporting `batch/v1` avoids when that is available to users.

## Problem - what in Jaeger blocks you from solving the requirement?

The `batch/v1beta1` API will no longer be served by the API starting in the 1.25 release of Kubernetes, supporting `batch/v1` avoids when that is available to users.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Probably use `common.capabilities.cronjob.apiVersion` from the [Bitnami Common Library Chart
](https://github.com/bitnami/charts/tree/master/bitnami/common) similar to how Ingress resources utilize it.

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125 indicates there are no notable changes so probably sufficient to replace the `apiVersion` lines with something like `apiVersion: {{- include common.capabilities.cronjob.apiVersion $ }}`. (or whatever the exact syntax is)

**Comment by mehta-ankit** [comment]
yup as you said `apiVersion: {{ include "common.capabilities. cronjob.apiVersion" $ }}`
https://github.com/bitnami/charts/blob/master/bitnami/common/templates/_capabilities.tpl#L43
Would you like to make a PR for this change @maristgeek  ?? 😃

**Comment by maristgeek** [comment]
Don't let me hold it up, it will be a while (days) before I will have the 5 minutes free and not feel like I should be doing something else.
