### ISSUE TITLE
ES_TAGS_AS_FIELDS_ALL gives an Array instead of Dictionary.

### ISSUE THREAD

**Issue by mayankkthr** [jaegertracing/helm-charts#360]
**Describe the bug**
ES_TAGS_AS_FIELDS_ALL gives an Array instead of Dictionary for tags.
Also **tag** is renamed as **tags**.

This happened after upgrading from  jaeger-0.51.5 to jaeger-0.55.0.

**To Reproduce**
1. Install jaeger-0.51.5 using helm with elasticsearch storage and ES_TAGS_AS_FIELDS_ALL = true environment variable.
2. Generate some traces.
3. Upgrade to jaeger-0.55.0 and then see the difference in tag data by generating new traces.

**Expected behavior**
Field name should be tag and not tags. The data should be in Dictionary format and not an Array.

If this is some new enhancement, then please point me to the related documentation.
I do not see this change mentioned in release notes.

**Comment by mehta-ankit** [comment]
So as I understand it is a command line param that can be passed like this:
```
cmdlineParams:
      es.tags-as-fields.all: true
```
So i don't get it when you say `tag` was renamed to `tags` ?? I do not see a K8s resource in jaeger helm chart specifying this flag ?

Are you saying Jaeger changed the flag from `es.tag-as-fields.all` -> `es.tags-as-fields.all` ??
https://www.jaegertracing.io/docs/1.33/cli/
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/22157398/165104432-3886c24b-04e0-4717-862d-8b636373db75.png">

If not then i am not able to wrap my head around this issue, like how did it break from a helm chart upgrade ? 

Can you please share how you pass in that flag using the jaeger helm chart.

**Comment by mayankkthr** [comment]
I am passing this flag in values.yaml file.

![image](https://user-images.githubusercontent.com/16535144/165113445-5dad85ef-bd6b-4ff2-9531-79c735fb7cc1.png)

Expected data in trace [Notice the **tag** in yellow and data type of tag was dictionary]

![image](https://user-images.githubusercontent.com/16535144/165114404-7fda42cf-8d77-493b-b44c-20f1c7e86b3d.png)

Data after upgrading to jaeger-0.55.0 [Notice the **tags** in yellow and data type is Array. **tag** (field without s) is removed]

![image](https://user-images.githubusercontent.com/16535144/165114939-271102b0-db2f-4f2a-8ab9-e2601a741698.png)

**Comment by mehta-ankit** [comment]
I see few things here:
1) One thing I see is that `.Values.elasticsearch.extraEnv` as you pass in your values will directly go to the elasticsearch helm chart. To set ES extraEnv params on Jaeger chart so relevant components get it, you ll have to set it as 
`.Values.storage.elasticsearch.extraEnv`.
see here: https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/_helpers.tpl#L370
which goes into the Helm template variable `elasticsearch.env` and that gets used by `storage.env` and that finally gets used by [collector deployment ](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/collector-deploy.yaml#L89) and [Ingester deployment](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/ingester-deploy.yaml#L74).

So just setting it in `.Values.storage.elasticsearch.extraEnv` should add that env var to your collector deployment.

2) Between 0.51.5 and 0.55 Jaeger appVersion changed from 1.28 to 1.30, but other than that I do not see any helm chart changes that could have affected your use case.

3) Can you check Elasticsearch version you had installed with 0.51.5 and if that changed for you and Elasticsearch itself has changed the structure of how it shows the tags ?

**Comment by mayankkthr** [comment]
1. Tried but it does not solve my problem.
2. Thank you for checking.
3. Elasticsearch version has changed. I compared its source code changes but it does not show any specific change related to my use case. Further, I think - The data, whatever it is, is sent by Jaeger. Elasticsearch just stores the data the way it comes in.

**Comment by mehta-ankit** [comment]
Ok I found something else.
In `0.55.0` there was a fix to pass in `.Values.collector.extraEnv` to the collector deployment:
See this change: https://github.com/jaegertracing/helm-charts/pull/340/files#diff-81fe0720416ba8af22ef7348b62728c6b46fefac5617d7b51ecc9fdcaca761f4R63

before this change what you were passing was not working but after the change the env var was being passed to the collector.
<img width="541" alt="image" src="https://user-images.githubusercontent.com/22157398/165170409-7a44c403-1b8b-4ef4-8094-68c6880de587.png">

**Comment by mehta-ankit** [comment]
That is the correct structure where u see tag as a dictionary and not as an array. Look at this issue: https://github.com/jaegertracing/jaeger/issues/906
which was solved by this PR: https://github.com/jaegertracing/jaeger/pull/1018 that added support for `es.tag-as-fields.all`

**Comment by mayankkthr** [comment]
es.tag-as-fields.all helped. Thanks @mehta-ankit .

**Comment by mayankkthr** [comment]
My use case is not related to Kibana currently. So I am fine with it.
I am not sure how **es.tag-as-fields.all** worked for me. I will thoroughly check on this before moving things to Production.
I placed ES_TAG_AS_FIELDS_ALL = true on Jaeger collector and this is how I see the response now.
The content highlighted in yellow is what my code reads.
The content highlighted in blue is what does not matter to me at the moment.

![image](https://user-images.githubusercontent.com/16535144/165310151-7c9f86c0-8716-46be-86a4-bd925b903eae.png)
