### ISSUE TITLE
[jaeger] cassandra keyspace for spark cronjob does not match 

### ISSUE THREAD

**Issue by naseemkullah** [jaegertracing/helm-charts#38]
https://github.com/jaegertracing/helm-charts/blob/b9c301594e8e98b5b41c796f2a25bd2d9a3489ae/charts/jaeger/templates/spark-cronjob.yaml#L40

Should be changed to match changes in #31 

cc @arpitjindal97

**Comment by arpitjindal97** [comment]
okay, I will make change there.

Also, should we change the default of keyspace to `jaeger_v1_dc1` or `jaeger_v1_test` . Addressing the break in helm chart

**Comment by naseemkullah** [comment]
solved via #35
