### ISSUE TITLE
[Feature]: Add option to enable OpenTelemetry in Collector

### ISSUE THREAD

**Issue by christian-morin** [jaegertracing/helm-charts#382]
### Requirement

Ability to enable the Jaeger Collector to support OpenTelemetry from the Helm Chart

### Problem

Jaeger now natively supports OpenTelemetry as described in https://medium.com/jaegertracing/introducing-native-support-for-opentelemetry-in-jaeger-eb661be8183c. However, this feature needs to be enabled in the collector. This can be done by setting extraEnv COLLECTOR_OTLP_ENABLED=true, but further ports need to be exposed to be able to utilise the feature (at least if you want to use both otlp and the “classic” Jaeger formats). There's currently no way to add these ports, so it would simply be great if this was added to the helm chart.

### Proposal

Add property otlpEnabled to Collector. If set to true, the COLLECTOR_OTLP_ENABLED=true is set for the Collector, and the standard ports 4317 and 4318 are exposed (and is able to be overridden if needed).

**Comment by vasicvuk** [comment]
This should be also added for all-in-one deployment...
