### ISSUE TITLE
[Feature]: TTL setting for esIndexCleaner jobs after completion

### ISSUE THREAD

**Issue by Mahagon** [jaegertracing/helm-charts#393]
### Requirement

As a Kubernetes Administrator
I would like to set ttlSecondsAfterFinished for the es index cleaner
so that old jobs in completed state get removed sooner

### Problem

![image](https://user-images.githubusercontent.com/874007/185359532-7ed6f3e7-74c0-48f8-990f-5a54375f884c.png)

Old jobs in completet state remain for hours

### Proposal

Like in esRollover i would like ttlSecondsAfterFinished entry for esIndexCleaner
https://github.com/jaegertracing/helm-charts/blob/eff00f612e3acf0cb335b169c6186ff581a40d2b/charts/jaeger/values.yaml#L692

**Comment by mehta-ankit** [comment]
I know esRolllover is a [job](https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/templates/es-rollover-hook.yml#L3)
and i am guessing jobTemplate.spec should be able to take this `ttlSecondsAfterFinished` flag which is available on a [job](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/)
Sounds like a good addition.

@Mahagon would you like to make a PR with this change ? Happy to take the contribution.
