### ISSUE TITLE
[jaeger] Use elastic chart as elasticsearch dependency

### ISSUE THREAD

**Issue by naseemkullah** [jaegertracing/helm-charts#4]
The optional elasticsearch dependency chart should be https://github.com/elastic/helm-charts/tree/master/elasticsearch

**Comment by scottrigby** [comment]
Do you want to explore this as an alternative dependency in a PR?

**Comment by naseemkullah** [comment]
Yes, sounds good, I'd prefer to completely remove the current deprecated elasticsearch dependency and swap in the new and improved dependency instead of manage values for both. Is that ok provided our disclaimer?

**Comment by scottrigby** [comment]
Whichever chart dependency you prefer 😄

**Comment by naseemkullah** [comment]
Solved via #11
