### ISSUE TITLE
New release for jeager-operator

### ISSUE THREAD

**Issue by giautm** [jaegertracing/helm-charts#404]
### Requirement

Hello, I would to use the new version of jeager-operator via the helm-chart release. Because it has a new field `pathType` so I have to update the CRD manually via kubectl. It will be great if you can create a new release for it, please.

https://github.com/jaegertracing/jaeger-operator/pull/2066

### Problem

Unable to use the current helm chart for the new version of `jeager-operator`

### Proposal

Create new release

**Comment by giautm** [comment]
Hello @mjnagel, sorry for directly tagging. Do you have any plans for the new release? When the next release is happen?

**Comment by mjnagel** [comment]
@giautm I can get a PR up today probably, but it's also not too tricky if you'd like to try and tackle it. I typically grab the installation manifest release asset from the operator and sync the CRD file + update image/versioning. There's rarely other changes beyond that although it can be good to validate the diffs between installation manifests.

**Comment by giautm** [comment]
Thank you, maybe in the next time I will take the pr. I'm new here. So I dont want to break things.
