### ISSUE TITLE
[Feature]: allow to specify `pathType` for the ingress

### ISSUE THREAD

**Issue by omerlh** [jaegertracing/helm-charts#423]
### Requirement

Using Jaeger query UI with AWS ALB ingress

### Problem

When using ALB ingress, `pathType` must be `Prefix`, otherwise the UI is not working.

### Proposal

Add a way in the `values.yaml` to specify the `pathType`

**Comment by Laakso** [comment]
Use `basePath: /*` with ALB as a workaround.
