### ISSUE TITLE
[Bug]: Jaeger cant be deployed with autoscaling in kubernetes 1.25

### ISSUE THREAD

**Issue by razorsk8jz** [jaegertracing/helm-charts#429]
### What happened?

on a version of Kubernetes 1.25+ when trying to deploy Jaeger with autoscaling enabled you run into the error 

```Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"```

based on https://kops.sigs.k8s.io/horizontal_pod_autoscaling/ it appears that the hpa needs updated to autoscaling/v2beta2 or atleast support to be able to change the autoscaling api version

### Steps to reproduce

1. Have a version of kubernetes on verion 1.25+ 
2. Attempt to deploy jaeger with autoscaling enabled

### Expected behavior

Should deploy correctly with autoscaling enabled

### Jaeger backend version

0.64.0

**Comment by DrFaust92** [comment]
https://github.com/jaegertracing/helm-charts/pull/439 this should fix it
