### ISSUE TITLE
[Feature]: make replicas spec a Helm variable rather than hardcoding to `replicas: 1`

### ISSUE THREAD

**Issue by lisenet** [jaegertracing/helm-charts#493]
### Requirement

We'd like to be able to specify the number of replicas using Helm.

### Problem

The replicas count is hardcoded to 1.

### Proposal

Make the replicas spec a Helm variable.

**Comment by pavelnikolov** [comment]
@lisenet why would you even want to have more than one replica of a pod that has in-memory data. The pods don't share data in any way.
