### ISSUE TITLE
[Feature]: Update helm-chart to use elasticsearch 8+

### ISSUE THREAD

**Issue by Stevenpc3** [jaegertracing/helm-charts#532]
### Requirement

As a user of the helm-chart I would like the chart.yaml dependency of Elasticsearch to be updated to version 8+ so that I can use the latest or current versions of Elasticsearch with Jaeger.

### Problem

Jeager was recently updated to support Elasticsearch version 8+ https://github.com/jaegertracing/jaeger/releases/tag/v1.52.0

But the chart still points to version 7.11.1 https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/Chart.yaml#L35

Blindly updating this likely will not work since the values.yaml settings are for the older verison and the index values have changed so things like "esIndexCleaner" and "esRollover" and "esLookback" will need to be updated to work with the new version.

### Proposal

Someone tests the newer version of Elasticsearch and modifies the values.yaml and templates to properly clean and manage the new indexes.

### Open questions

Is this currently planned somewhere else?

**Comment by Stevenpc3** [comment]
Seeing how the old elasticsearch chart is deprecated and the suggestion is to use ECK now but has license issues to consider.

I suggest doing what we did when we needed to use elasticsearch outside of jaeger which is use the elasticsearch bitnami chart.

Ironically... we were going to use the bitnami jaeger chart but it is woefully under developed compared to other charts.

**Comment by Stevenpc3** [comment]
helm charts were just updated to 1.53 https://github.com/jaegertracing/helm-charts/commit/94950b7c837ccdde786ffb3308132cc759a374ca.

This implies that I can use elasticsearch 8+ .  Any work on ensuring this is true and updateing the chart to point to the new bitnami charts?  Bitnami charts have changed so I assume jeager charts would require a number of updates.  For example elasticsearch.esConfig is no longer avaialble in the bitnami charts

**Comment by Stevenpc3** [comment]
Awesome thanks! I'll try to get to it this week.

**Comment by Stevenpc3** [comment]
So we finally go to test this and it appears to work and esIndexCleaner works.  BUT...

This breaks spark.  It will throw an error stating that it only supports version 7 of elasticsearch and requires hadoop.

**Comment by Stevenpc3** [comment]
Yeah I'll give it a go tomorrow. I'm just using the default from the chart. If that works then I guess the chart or Jaeger needs updating. This is pulling the image that Jaeger published. I see it was updated so should work https://github.com/jaegertracing/spark-dependencies/commit/a5e17365cecfd7650ef47a1fe26f617189095a77

If the registry defaults to docker then we likely should update the registry in the chart to point to the right place otherwise it will keep happening for everyone.

**Comment by Stevenpc3** [comment]
going to close this issue and keep the spark part in a different issue

**Comment by sergeykad** [comment]
I fixed it by adding the registry to my configuration as follows. 
Can this be merged into the official Helm charts?

```yaml
spark:
  enabled: true
  image:
    registry: ghcr.io
```
