### ISSUE TITLE
[Feature]:  global.PullSecerts

### ISSUE THREAD

**Issue by HeartConnector** [jaegertracing/helm-charts#548]
### Requirement

https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml#L6 

### Problem

Mb has global.pullSecrets is more useful and convenient

**Comment by bens545** [comment]
.global.imagePullSecrets is already supported, but not documented.

https://github.com/jaegertracing/helm-charts/blob/d4e163e1311df2596aabb7db1aedc05169a71396/charts/jaeger/templates/_helpers.tpl#L541

https://github.com/bitnami/charts/blob/dd62c04776102f90eb54a1f2cf1c901b03af6b3e/bitnami/common/templates/_images.tpl#L33
