### ISSUE TITLE
[Jaeger] Add a batch job to clean up ElasticSearch indices

### ISSUE THREAD

**Issue by mehta-ankit** [jaegertracing/helm-charts#57]
I was wondering if there has been any discussion regarding adding a K8s job to the Helm chart for Jeager to clean up elasticsearch indices (for example: delete indices that are n days old, since each ES index is timestamped by day).

The following image is already published.
https://hub.docker.com/r/jaegertracing/jaeger-es-index-cleaner

**Comment by mehta-ankit** [comment]
@naseemkullah Thoughts ?

**Comment by naseemkullah** [comment]
That's a great point, we could allow for the creation of https://github.com/helm/charts/tree/master/stable/elasticsearch-curator as a subchart or use the recommended practice of ILM which would be configured in whatever manner the elastic chart recommend. But IMHO there should be no additional template to this jaeger chart.

**Comment by naseemkullah** [comment]
On second thought, if jaeger are maintaining an image specifically for this, perhaps we could indeed add it as a cronjob. 🤔 

@jpkrohling @yurishkuro Is there a reason operator does not recommend using elastic curator or built int ILM of elasticsearch for index deletion, but resort to a custom tool?

**Comment by mehta-ankit** [comment]
Also, if we end up deciding on a CronJob, i already have one for my purposes that i am using and can make a PR with that. 👍

**Comment by naseemkullah** [comment]
Sounds good @mehta-ankit , let's use the cronjob if that's what the operator does. It seems to run es-curator in any case.

**Comment by mehta-ankit** [comment]
This PR addresses this issue: https://github.com/jaegertracing/helm-charts/pull/60

**Comment by mehta-ankit** [comment]
@naseemkullah Should we just close this issue ?

**Comment by naseemkullah** [comment]
Yep! Solved via #60

**Comment by venukasu** [comment]
It would be very helpful if we can add support for passing ES_USERNAME & ES_PASSWORD similar to collector deploy and spark cronjob?

**Comment by naseemkullah** [comment]
💯 @venukasu Would you be willing to make a PR to add this?

**Comment by venukasu** [comment]
@naseemkullah Raised a PR #65 for adding  ES_USERNAME and ES_PASSWORD environment variable to the jaeger-es-index-cleaner job.
