### ISSUE TITLE
[Bug]: failed to list v1.IngressClass is forbidden for apigroup networking.k8s.io

### ISSUE THREAD

**Issue by surajnmandhare** [jaegertracing/helm-charts#593]
### What happened?

eflector.go:147] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: Failed to watch *v1.IngressClass: failed to list *v1.IngressClass: ingressclasses.networking.k8s.io is forbidden: User "system:serviceaccount:jaeger-operator:jaeger-operator" cannot list resource "ingressclasses" in API group "networking.k8s.io" at the cluster scope

### Steps to reproduce

Remove the Jaeger instance
Try to re-add it

### Expected behavior

Should not complain about permission

### Additional context

  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses

### Jaeger backend version

NAME                         	CHART VERSION	APP VERSION	DESCRIPTION                               jaeger/jaeger-operator       	2.55.0       	1.57.0     	jaeger-operator Helm chart for Kubernetes

**Comment by kravciak** [comment]
PR with the fix already in the queue https://github.com/jaegertracing/helm-charts/pull/592 ;)
