### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by naseemkullah** [jaegertracing/helm-charts#6]
Let's look at that in a separate PR. Here's an example that's kind of nice and also easy https://charts.fluxcd.io/

_Originally posted by @scottrigby in https://github.com/jaegertracing/helm-charts/pull/2_

**Comment by cpanato** [comment]
we setup this for Mattermost: https://helm.mattermost.com/ simple

**Comment by cpanato** [comment]
i liked the fluxcd maybe will clone :)

**Comment by naseemkullah** [comment]
Solve via #10
