### ISSUE TITLE
CI issues

### ISSUE THREAD

**Issue by naseemkullah** [jaegertracing/helm-charts#66]
Hello,
We have quite a few PRs unable to be merged because CI keeps failing.
Is there a way to skip CI?

In particular for this: https://github.com/jaegertracing/helm-charts/pull/62

I think https://github.com/actions/checkout/issues/23 has been an issue for many of these blocked PRs.

**Comment by jpkrohling** [comment]
In general, PRs can be merged even if CI is failing. What I typically do in the Jaeger Operator repository is to run the tests locally to verify that they aren't failing because of the PR. I'm not sure what's the policy in this repository, though.

**Comment by naseemkullah** [comment]
Can someone with admin access please disable "Require status checks to pass before merging." for this repo?

**Comment by jpkrohling** [comment]
Done

**Comment by naseemkullah** [comment]
Thanks @jpkrohling !
