### ISSUE TITLE
[jaeger] es.tags-as-fields.all field missing

### ISSUE THREAD

**Issue by vipinvkmenon** [jaegertracing/helm-charts#70]
The environment variable to support ES_TAGS_AS_FIELDS_ALL is missing in the chart.

**Comment by naseemkullah** [comment]
closed via #75

**Comment by naseemkullah** [comment]
We can add any ES related env var to https://github.com/jaegertracing/helm-charts/blob/fc87249b7f3b8a0a6e5fd891d7a7a52ef6e17cd4/charts/jaeger/values.yaml#L53 now. :)

Or command lint opt: https://github.com/jaegertracing/helm-charts/blob/fc87249b7f3b8a0a6e5fd891d7a7a52ef6e17cd4/charts/jaeger/values.yaml#L59
