### ISSUE TITLE
Use jaegertracing bot gh token

### ISSUE THREAD

**Issue by cpanato** [jaegertracing/helm-charts#9]
Can we set up a jaegertracing bot and use its GH token instead of the @scottrigby token? :)

besides the fact, if that somehow get leaked the scott's token will be used for other things and maybe have access to his repos.

**Comment by scottrigby** [comment]
@yurishkuro @jpkrohling would this be a good use of https://github.com/jaegerci-bot? We would need a personally access token with repo scope, from a user who has write access to this github project (details at: https://github.com/helm/chart-releaser-action#pre-requisites). You would not need to pass me this token directly, it could just be set directly by replacing the `CR_TOKEN` in this github project admin settings https://github.com/jaegertracing/helm-charts/settings/secrets.

**Comment by yurishkuro** [comment]
I've never heard of jaegerci-bot, I don't think we use it anywhere. I am not sure who owns it. cc @pavolloffay 

In other repos we are using a fake user `jaegertracingci` that does commits to the repository.

https://github.com/jaegertracing/jaeger-client-java/blob/028d3b0580cd4cd6b678a113d8c3ed6c3e2e25e6/.travis.yml#L37
https://github.com/jaegertracing/documentation/blob/cb157c985ca0fcbba27d849eebf182bf214bbff5/.travis.yml#L12

But that's not the same as having write access to the repository. If we can't find the owner of jaegerci-bot we can create another [machine user](https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users).

**Comment by scottrigby** [comment]
@yurishkuro sounds good, I'll wait to hear back 😄  I asked about @jaegerci-bot only because i saw that user is a [member](https://github.com/orgs/jaegertracing/people?utf8=%E2%9C%93&query=bot) of the jaegertracing org. PS if you want to connect about anything sensitive I'm [@r6by](https://keybase.io/r6by) on keybase

**Comment by scottrigby** [comment]
In 2 days I'll be offline for until the 2nd week in January, so to mitigate my risk during that time I made a temporary machine user https://github.com/jaegerbot. @yurishkuro I'm happy to transfer that to you whenever, or if you prefer a different machine user I can later delete that one. Either way, in the meantime I have update the `CR_TOKEN` in this repo with a new personal access token from the @jaegerbot user and added that user as a write collaborator to this gh project. I'd leave it to @yurishkuro to either close this issue or keep open depending on next desired steps.

**Comment by yurishkuro** [comment]
It looks like the whole reason for a personal token is a bug in the interaction of GH actions and GH pages (https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/true/page/2). Once it's addressed we should be able to use just the GH token, like we do with pushing auto commits to the other Jaeger repos.

**Comment by scottrigby** [comment]
Yes 👍 We'll also update the note on that in the [helm/chart-releaser-action readme](https://github.com/helm/chart-releaser-action#pre-requisites) when the actions bug is fixed.

**Comment by jpkrohling** [comment]
@jaegerci-bot seems to have been created by Red Hat QE. @kevinearls and/or @jkandasa might have access to the credentials and should be able to create the required tokens.

**Comment by jpkrohling** [comment]
> it could just be set directly by replacing the CR_TOKEN in this github project admin settings

Done! The `CR_TOKEN` has a token with `repo` scope for the `@jaegerci-bot` user. Let me know if you need anything else.

**Comment by scottrigby** [comment]
Great! I deleted the temporary jaegerbot I had made. All previous personal access tokens deleted.
