### ISSUE TITLE
Helm repository not working when github is down

### ISSUE THREAD

**Issue by eddycharly** [jaegertracing/helm-charts#94]
As helm charts are hosted on github, the repository is not available when github is down.

Are there any plan/reflection to move the repository in a safer place ?

Thanks

**Comment by naseemkullah** [comment]
Hi @eddycharly, it's true, if github is down then the charts become unavailable, despite this there are no plans to move them at this time.

**Comment by eddycharly** [comment]
Ok, thanks.
Do you know why github was chosen in the first place ?
Hosting a helm repo doesn’t require an infrastructure, a simple bucket is enough.

**Comment by naseemkullah** [comment]
Mostly due to the ease of following along https://github.com/helm/charts-repo-actions-demo to setup the hosting and CI

**Comment by eddycharly** [comment]
Ok, thanks.
Feel free to close the issue.

**Comment by naseemkullah** [comment]
Alright, thanks @eddycharly
