### ISSUE TITLE
[jaeger] Prometheus metrics

### ISSUE THREAD

**Issue by Jasstkn** [jaegertracing/helm-charts#96]
Hey!
I wonder why there is no ServiceMonitor for jaeger components? Is there any issues with it? If it's not, I'll happy to contribute this improvement. Let me know, what do you think about it =) 

I see list of ports and default path in docs: https://www.jaegertracing.io/docs/1.17/monitoring/

**Comment by naseemkullah** [comment]
Yes please, that would be great!

**Comment by naseemkullah** [comment]
Values file would look like this for each component that exposes a metrics port?

```
<component>:
...
  serviceMonitor:
    enabled: false
  ...
```

**Comment by Jasstkn** [comment]
@naseemkullah yes. =)
