### ISSUE TITLE
[jaeger] Cannot install jaeger

### ISSUE THREAD

**Issue by schmurfy** [jaegertracing/helm-charts#99]
I tried using this command:
```
helm install -n jaeger jaegertracing/jaeger
```

And I got:
```
Error: validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

I think this is related to #97 as I can install version 0.27.0 of this chart fine.

**Comment by naseemkullah** [comment]
Hi @schmurfy I think this has been fixed, can you try `helm repo update` and try again?

**Comment by schmurfy** [comment]
Hi, I tried again and now I have this wall of text as error:

Error: Job.batch "jaeger-cassandra-schema" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"jaeger-cassandra-schema", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"controller-uid":"6896ea4d-8629-11ea-b261-42010a8401ba", "job-name":"jaeger-cassandra-schema"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:"jaeger-cassandra-schema", Image:"jaegertracing/jaeger-cassandra-schema:1.17.1", Command:[]string(nil), Args:[]string(nil), WorkingDir:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar{core.EnvVar{Name:"MODE", Value:"prod", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"CASSANDRA_SERVERS", Value:"jaeger-cassandra", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"CASSANDRA_PORT", Value:"9042", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"CASSANDRA_KEYSPACE", Value:"jaeger_v1_test", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"CASSANDRA_USERNAME", Value:"user", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"CASSANDRA_PASSWORD", Value:"", ValueFrom:(*core.EnvVarSource)(0xc003df5500)}, core.EnvVar{Name:"CQLSH_HOST", Value:"jaeger-cassandra", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"DATACENTER", Value:"dc1", ValueFrom:(*core.EnvVarSource)(nil)}, core.EnvVar{Name:"KEYSPACE", Value:"jaeger_v1_test", ValueFrom:(*core.EnvVarSource)(nil)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy:"IfNotPresent", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:"OnFailure", TerminationGracePeriodSeconds:(*int64)(0xc013f68058), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceAccountName:"jaeger-cassandra-schema", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.PodSecurityContext)(0xc00fd68ee0), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), EnableServiceLinks:(*bool)(nil)}}: field is immutable

If I add back `--version 0.27.0` everything works fine

**Comment by naseemkullah** [comment]
Hi @schmurfy , 
try running helm with the `--force` flage,
if that does not work, delete the job `kubectl delete job jaeger-cassandra-schema` and then try upgrading again.

**Comment by schmurfy** [comment]
it worked :)
